### ISSUE TITLE
Collapse Ombi on Homepage when there is no content [Feature request]

### ISSUE THREAD

**Issue by JohanSF** [Burry/organizr-v2-plex-theme#1]
Requesting that Ombi be collapsed on the Homepage when there is no content in it.

With Plex theme:
![image](https://user-images.githubusercontent.com/6782603/42675836-0b8be09c-8676-11e8-846d-58c870bb06b6.png)

With Organizr theme:
![image](https://user-images.githubusercontent.com/6782603/42675868-1e8f2ffa-8676-11e8-86a6-339e13473b71.png)

**Comment by Burry** [comment]
Fixed in latest release

**Comment by JohanSF** [comment]
Did you forget to push it? a new release was made but the fix is not in the source code. I still have the issue.

**Comment by Burry** [comment]
Did another commit and push so it's definitely in there now. Check your cache

<img width="361" alt="screen shot 2018-07-13 at 12 43 11 am" src="https://user-images.githubusercontent.com/1909420/42676528-c5141aca-8635-11e8-9f41-38ec982d91e6.png">

**Comment by JohanSF** [comment]
It was updated now and I updated the Plex.css file to the new one and restarted my organizr-v2 docker. But it still looks exactly like in my screenshot above. I have cleared my cache too.

**Comment by Burry** [comment]
Sorry I'm not sure what to tell you: I can no longer replicate the issue on my end, and the fix is in the stylesheet.

**Comment by JohanSF** [comment]
My bad - I made a mistake on my end. It works now, thank you very much you're awesome!
